markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]
title : Carlos Becker
production_url : http://caarlos0.github.com
description: "Througths, flamewars, utilities, tutorials, codes, projects andother things by Carlos Alexandro Becker."
disqus_shortname: caarlos0blog
author :
  name : Carlos Alexandro Becker
  github : caarlos0
  twitter : caarlos0
