markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]
title : codesavvy.send(Blog)!
production_url : http://codesavvy.github.com
description: "Througths, flamewars, utilities, tutorials, codes, projects and other things by Abdul Shajin."
disqus_shortname: codesavvysblog
analytics: UA-39282485-1
#gauges: 50f2b533613f5d7c8000000c
author :
  name : Abdul Shajin
  github : codesavvy
  twitter : rubysavvy
